name: Unit Tests

on:
  pull_request:
    branches: [ develop ]

env:
  AUTOMATICS_UNAME: ${{ secrets.AUTOMATICS_UNAME }}
  AUTOMATICS_PASSCODE: ${{ secrets.AUTOMATICS_PASSCODE }}

jobs:
  execute-unit-tests-on-pr:
    name: Execute unit tests in gtest test suite
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-device-mgt-service-test/native-platform:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: sh -c test/run_ut.sh


      - name: Copy l2 test results to runner
        run: |
          docker cp native-platform:/tmp/Gtest_Report /tmp/Gtest_Report
          ls -l
          ls -l /tmp/Gtest_Report

  upload-test-results:
    name: Upload L1 test results to automatic test result management system
    needs: execute-L1-tests-on-pr
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest
      volumes:
        - /tmp/Gtest_Report:/tmp/Gtest_Report
    steps:
      - name: Upload results
        if: github.repository_owner == 'rdkcentral'
        run: |
            echo "Contents in workspace directory"
            ls -l
            echo "==============================="
            echo "Contents in /tmp/L2_TEST_RESULTS"
            ls -l /tmp/Gtest_Report
            echo "==============================="
            git config --global --add safe.directory `pwd`
            gtest-json-result-push.py /tmp/Gtest_Report https://rdkeorchestrationservice.apps.cloud.comcast.net/rdke_orchestration_api/push_unit_test_results `pwd`
