name: Build Component in Native Environment

on:
  pull_request:
    branches: [ develop ]
    paths: ['**/*.c', '**/*.cpp', '**/*.cc', '**/*.cxx', '**/*.h', '**/*.hpp']

jobs:
  build-common-utilities-on-pr:
    name: Build common utilitiescomponent in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: native build
        run: |
          chmod +x cov_build.sh
          sh -e cov_build.sh

